title: Yash Yennam
logo: /assets/img/1635938374586.jpg
description: Yash Yennam is Machine Learning Engineer at a Fintech with experince in Investment Bank.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
